# Generated by Django 3.0.5 on 2020-04-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author',
            field=models.BooleanField(default=False),
        ),
    ]
