# Generated by Django 3.0.5 on 2020-05-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field=100, upload_to='public/profile_pictures/', width_field=100),
        ),
    ]
