# Generated by Django 3.0.5 on 2020-05-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_auto_20200501_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='public/profile_pictures/'),
        ),
    ]
