# Generated by Django 3.0.5 on 2020-05-03 12:51

import blogApp.models
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blogApp', '0014_post_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_on_view',
            field=models.ImageField(blank=True, upload_to=blogApp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
